### ISSUE TITLE
Change log level or capabilities.

### ISSUE THREAD

**Issue by hugueslamy** [platbr/kubernetes-health#1]
So far this is a good simple gem to add to your Kubernetes deployment.
I would like you opinion on how we could manage the verbosity of the logs. At the moment, it is fixed a debug level, but I would like enable or disable them but a configuration. Would it be better to fork than make a pull request ?

**Comment by platbr** [comment]
Hi, @hugueslamy,
Sorry about my late.
I addressed it using this approach in v3.2

## Customizing requests logs

```
Kubernetes::Health::Config.request_log_callback = lambda { |req, http_code|
  Rails.logger.debug "Kubernetes Health: Rack on Migrate - Request: Path: #{req.path_info} / Params: #{req.params} /  HTTP Code: #{http_code}"  rescue nil
}
```

I guess  it is flexible enough.

**Comment by hugueslamy** [comment]
Yes, you can set the log file and the level that you want. 
I just don't know if there's any performance hit you recreate a debugger object each time. Most likely not an issue.

**Comment by platbr** [comment]
> Yes, you can set the log file and the level that you want.
> I just don't know if there's any performance hit you recreate a debugger object each time. Most likely not an issue.

On my  exemple it is using the already defined logger from Rails stack, it is not defining a new object on each request.
I guess this approach is better because it will "copy" the Rails behaviour.
It is possible change the log level just changing `Rails.logger.debug` to `Rails.logger.WANTED_LEVEL`.
