### ISSUE TITLE
[Feature] Rack 3 support

### ISSUE THREAD

**Issue by danilrwx** [platbr/kubernetes-health#6]
After rack upgrades to 3.0, Rack::Handler moved to separate gem
https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#binrackup-rackserver-rackhandlerand--racklobster-were-moved-to-a-separate-gem

Possible solution:
```ruby
server = defined?(Rackup::Handler) ? Rackup::Handler : Rack::Handler
server.run Kubernetes::Health::RackOnSidekiq.new, Port: Kubernetes::Health::Config.metrics_port
```

**Comment by platbr** [comment]
Hi danilrwx, sorry about this delay =).
It's done. You can try it on 3.14.0

**Comment by matthewtusker** [comment]
Resurrecting this, we're trying to use `kubernetes-health` but it's not working. We don't use Rackup in our apps, so neither handler exists. Should Rackup be included as a dependency?
