### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by thayol** [platbr/kubernetes-health#7]
Hi,

I would like to include this gem into one of our projects but this gem has no license. Having no license can mean full ownership and copyright over the code which would forbid me from including it in for-profit projects.

An explicit license would help with knowing the legal boundaries. If you wish to set no restrictions, I suggest the [The Unlicense](https://opensource.org/license/unlicense).

More about licenses in the GitHub docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by platbr** [comment]
Done =)

**Comment by platbr** [comment]
Done =D
